services:
  bot:
    build: .
    container_name: telegram-bot
    env_file:
      - .env
    # Если нужно "пробросить" порт для webhook,
    # то указываем, например: "3000:3000".
    # В нашем случае используется long polling, так что доступ к порту не требуется,
    # но вот пример вам на будущее:
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tg_chatbot

    ports:
      - '3307:3306'
    networks:
        - app-network

networks:
  app-network:
